environment:
  name: test
  project: cdf-bootcamp-30-test
  validation-type: test
  selected:
  - modules/
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee 
   
variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
        data_developer_source_id: 0e61e9f9-8242-4da5-9228-4682baf6f9c4

      ice_cream_api:
        icapi_extractors_source_id: 39376f27-8890-44f0-8b07-bd95fb48c689
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
       

 
      use_cases:
        oee:
          data_pipeline_oee_source_id: 646b5cb3-1f08-4650-bea0-6318d0507f31
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
 